version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://db:27017/minilemon
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - db

  db:
    image: mongo:7.0.7
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: minilemon
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
