name: MINILEMON SKILL TEST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MONGODB_URI: mongodb://localhost:27017/minilemon
  NODE_ENV: test
  PORT: 3000

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.0]
        mongodb-version: ['7.0.7']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm ci

      - name: Intall env-secrets
        run: npm install env-encryption

      - name: Decrypt env-secrets
        run: npx env-encryption decrypt --key ${{secrets.ENV_KEY}} --filename .env

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
